//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public long Id_Pedido { get; set; }
        public string Id_Estado_Pedido { get; set; }
        public double Monto { get; set; }
        public string Descripcion { get; set; }
        public string Id_Producto { get; set; }
    }
}
